# Generated by Django 3.2.9 on 2021-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='pics')),
                ('decs', models.TextField()),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='photo')),
                ('dec', models.TextField()),
            ],
        ),
    ]
